# Generated by Django 5.2.5 on 2025-10-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team_subsidy_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subsídio da Equipa Recebido'),
        ),
    ]
