# Generated by Django 5.2.5 on 2025-10-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_team_subsidy_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team_subsidy_received',
        ),
    ]
