# Generated by Django 5.2.5 on 2025-10-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_team_subsidy_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='app_download_link',
            field=models.URLField(default='#', help_text='A URL direta para o APK ou para a página de download do aplicativo.', verbose_name='Link de Download do App (APK)'),
        ),
    ]
