# Generated by Django 5.2.5 on 2025-10-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_platformsettings_app_download_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='app_download_link',
        ),
    ]
